{% set name = "jaq" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/01mf02/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 64b3431970cd4c27f3c4e665913218f44a0f44be7e22401eea34d52d8f3745a9

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/01mf02/{{ name }}
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: JQ clone focussed on correctness, speed, and simplicity
  dev_url: https://github.com/01mf02/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
