context:
  version: "2.2.0"

package:
  name: jaq
  version: ${{ version }}

source:
  url: https://github.com/01mf02/jaq/archive/v${{ version }}.tar.gz
  sha256: eee6a4d608c31c12c82644f1cdb69cfed55bb079806ec939e4de486bb252c631

build:
  number: 1

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - jaq --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: JQ clone focussed on correctness, speed, and simplicity
  homepage: https://github.com/01mf02/jaq
  repository: https://github.com/01mf02/jaq

extra:
  recipe-maintainers:
    - danielnachun
