context:
  version: "3.0.0"

package:
  name: jaq
  version: ${{ version }}

source:
  url: https://github.com/01mf02/jaq/archive/v${{ version }}.tar.gz
  sha256: c56948c90d0c3566c8b33eedd9fa61587ffbb2feef7d78172955876d6e10a315

build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses

tests:
  - script:
      - jaq --help

about:
  license: MIT
  license_file:
    - LICENSE-MIT
    - THIRDPARTY.yml
  summary: JQ clone focussed on correctness, speed, and simplicity
  homepage: https://github.com/01mf02/jaq
  repository: https://github.com/01mf02/jaq

extra:
  recipe-maintainers:
    - danielnachun
